AWSTemplateFormatVersion: '2010-09-09'
Description: Attach a policy to an existing IAM user or role that allows assuming a specified role across any AWS account.

Parameters:
  Entity:
    Type: String
    Description: The ARN of the existing IAM user or role to which the policy will be attached.

  AssumableRoleName:
    Type: String
    Default: datamasque-crossaccount-role
    Description: The name of the role that the user or role should be allowed to assume across any account.

  PolicyName:
    Type: String
    Default: datamasque-crossaccount-policy
    Description: The name of the managed policy to be created.

Resources:
  AssumeRolePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Ref PolicyName
      Description: 'Policy that grants permissions to assume specified role across any AWS accounts.'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 'sts:AssumeRole'
            Resource: !Sub 'arn:aws:iam::*:role/${AssumableRoleName}'
      Roles:
        - !Ref Entity

Outputs:
  ManagedPolicyArn:
    Description: 'ARN of the managed policy created to allow cross-account role assumption.'
    Value: !Ref AssumeRolePolicy
