AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy an IAM role with read-only access to S3 within a single account for DataMasque access.

Parameters:
  DmRoleName:
    Type: String
    Description: The ARN of the DataMasque instance IAM role to which the policy will be attached.

  CrossAccountRole:
    Type: String
    Description: IAM role name that is assumed by the DataMasque application to execute masking runs on S3 buckets.

  DestinationBuckets:
    Type: CommaDelimitedList
    Description: Comma separated ARNs of target S3 buckets on which masked data is written.

  SourceBuckets:
    Type: CommaDelimitedList
    Description: Comma separated ARNs of source S3 buckets on which data needs to be masked.

  SourceBucketsPrefixes:
    Type: CommaDelimitedList
    Description: Comma separated prefixes of source S3 buckets from which data needs to be masked.

  DestinationBucketsPrefixes:
    Type: CommaDelimitedList
    Description: Comma separated prefixes of destination S3 buckets from which data needs to be masked.

Resources:
  S3CrossAccountRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref DmRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Ref DmRoleName
            Action: "sts:AssumeRole"
      MaxSessionDuration: 3600
      Policies:
        - PolicyName: "datamasque-crossacount-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ListBucketInfo
                Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketAcl
                  - s3:GetBucketPolicyStatus
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetBucketObjectLockConfiguration
                  - s3:GetEncryptionConfiguration
                Resource: !Split
                  - ","
                  - !Join
                    - ","
                    - - !Join [",", !Ref SourceBuckets]
                      - !Join [",", !Ref DestinationBuckets]
              - Sid: ReadBucket
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Ref SourceBucketsPrefixes
              - Sid: ReadWriteDeleteAccess
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Ref DestinationBucketsPrefixes

Outputs:
  DatamasqueCrossaccountRole:
    Description: "DataMasque Role for crossaccount bucket access."
    Value: !GetAtt S3CrossAccountRole.Arn
